# Generated by Django 4.1 on 2022-08-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth_diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='detail_news',
            name='detail',
        ),
        migrations.AddField(
            model_name='diary',
            name='keyword',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Detail_news',
        ),
        migrations.AddField(
            model_name='news',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earth_diary.diary'),
        ),
        migrations.AddField(
            model_name='image',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earth_diary.diary'),
        ),
    ]
